import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';

function grantAdmin(email, dataDir) {
  const result = spawnSync(process.execPath, ['scripts/grant-admin.js', email], {
    cwd: process.cwd(), env: { ...process.env, DATA_DIR: dataDir }, encoding: 'utf8'
  });
  assert.equal(result.status, 0, result.stderr);
}

test('öğrenci pazarı ve Dayanışma akışları', async t => {
  const temp = mkdtempSync(path.join(os.tmpdir(),'unipazar-test-'));
  const port = 31000 + Math.floor(Math.random()*1000);
  const base = `http://127.0.0.1:${port}`;
  const server = spawn(process.execPath,['server.js'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),DATA_DIR:path.join(temp,'data'),UPLOAD_DIR:path.join(temp,'uploads'),ADMIN_EMAIL:'admin@unipazar.local',NODE_ENV:'test',TEST_EMAIL_CODES:'1',SMTP_HOST:'',SMTP_FROM:''},stdio:'ignore'});
  t.after(async()=>{
    await new Promise(resolve=>{server.once('exit',resolve);server.kill();setTimeout(resolve,1500);});
    rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100});
  });
  for(let i=0;i<50;i++){
    try { if((await fetch(base+'/api/me')).ok) break; } catch {}
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  const users = {};
  async function request(path, method='GET', body, user){
    const headers={}; if(user?.cookie) headers.cookie=user.cookie;
    if(body && !(body instanceof FormData)) headers['content-type']='application/json';
    const res=await fetch(base+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});
    const data=await res.json();
    if(user && res.headers.get('set-cookie')) user.cookie=res.headers.get('set-cookie').split(';')[0];
    return {status:res.status,data};
  }
  async function makeUser(key,email,university='İstanbul Teknik Üniversitesi',needsSupport=false){
    const user=users[key]={cookie:''};
    const registered=await request('/api/register','POST',{name:key,email,password:'strong-password-123',phone:'05551234567',university,needsSupport},user);
    assert.equal(registered.status,201);
    assert.ok(registered.data.devCode);
    const verified=await request('/api/verify-email','POST',{email,code:registered.data.devCode},user);
    assert.equal(verified.status,200);
    user.id=verified.data.user.id;
    return user;
  }
  const admin=await makeUser('admin','admin@unipazar.local');
  assert.equal((await request('/api/admin/queue','GET',null,admin)).status,403);
  grantAdmin('admin@unipazar.local',path.join(temp,'data'));
  assert.equal((await request('/api/me','GET',null,admin)).data.user.role,'admin');
  const seller=await makeUser('seller','seller@example.com');
  const buyer=await makeUser('buyer','buyer@gmail.com','İstanbul Teknik Üniversitesi',true);
  const regular=await makeUser('regular','regular@gmail.com');
  const outsider=await makeUser('outsider','outsider@outlook.com','Boğaziçi Üniversitesi');
  assert.equal((await request(`/api/admin/accounts/${buyer.id}/message`,'POST',{},regular)).status,403);
  const direct=await request(`/api/admin/accounts/${buyer.id}/message`,'POST',{},admin);
  assert.equal(direct.status,200);
  const directId=direct.data.conversationId;
  assert.equal((await request(`/api/admin/accounts/${buyer.id}/message`,'POST',{},admin)).data.conversationId,directId);
  assert.equal((await request(`/api/conversations/${directId}/messages`,'POST',{body:'Yönetimden bilgi'},admin)).status,201);
  assert.equal((await request('/api/unread-count','GET',null,buyer)).data.count,1);
  assert.ok((await request('/api/conversations','GET',null,buyer)).data.conversations.some(c=>c.id===directId && c.listing_id===null));
  assert.equal((await request(`/api/conversations/${directId}/messages`,'GET',null,outsider)).status,404);
  assert.equal((await request(`/api/conversations/${directId}/messages`,'GET',null,buyer)).data.messages[0].body,'Yönetimden bilgi');
  assert.equal((await request(`/api/conversations/${directId}/messages`,'POST',{body:'Teşekkürler'},buyer)).status,201);
  const ownMessage=(await request(`/api/conversations/${directId}/messages`,'GET',null,admin)).data.messages[0];
  assert.ok(ownMessage.read_at);
  assert.equal((await request(`/api/messages/${ownMessage.id}`,'PATCH',{body:'Düzenlenen mesaj'},outsider)).status,404);
  assert.equal((await request(`/api/messages/${ownMessage.id}`,'DELETE',null,buyer)).status,404);
  assert.equal((await request(`/api/messages/${ownMessage.id}`,'PATCH',{body:'Düzenlenen mesaj'},admin)).status,200);
  assert.equal((await request(`/api/conversations/${directId}/messages`,'GET',null,buyer)).data.messages[0].body,'Düzenlenen mesaj');
  assert.equal((await request(`/api/messages/${ownMessage.id}`,'DELETE',null,admin)).status,200);
  assert.equal((await request(`/api/conversations/${directId}/messages`,'GET',null,buyer)).data.messages[0].body,'Bu mesaj silindi.');

  assert.equal((await request(`/api/admin/accounts/${seller.id}/listings`,'GET',null,regular)).status,403);
  assert.equal((await request('/api/listings')).data.listings.length,0);
  const universityList=await request('/api/universities');
  assert.ok(universityList.data.universities.length >= 200);
  assert.ok(universityList.data.universities.includes('İstanbul Teknik Üniversitesi'));
  assert.equal((await request('/api/register','POST',{name:'wrong',email:'wrong@example.com',password:'strong-password-123',phone:'05551234567',university:'Örnek Üniversitesi'})).status,400);
  const unverified=await request('/api/register','POST',{name:'pending',email:'pending@yahoo.com',password:'strong-password-123',phone:'05551234567',university:'İstanbul Teknik Üniversitesi'});
  assert.equal(unverified.status,201);
  assert.equal((await request('/api/login','POST',{email:'pending@yahoo.com',password:'strong-password-123'})).status,200);
  assert.equal((await request('/api/admin/queue','GET',null,admin)).data.support.length,0);
  assert.equal((await request('/api/register','POST',{name:'pending',email:'pending@yahoo.com',password:'strong-password-123',phone:'05551234567',university:'İstanbul Teknik Üniversitesi'})).status,409);
  assert.equal((await request('/api/login','POST',{email:'buyer@gmail.com',password:'wrong'})).status,401);
  assert.equal((await request('/api/login','POST',{email:'unknown@example.com',password:'strong-password-123'})).status,401);
  const remembered={cookie:''};
  const rememberLogin=await request('/api/login','POST',{email:'buyer@gmail.com',password:'strong-password-123',phone:'05551234567',rememberMe:true},remembered);
  assert.equal(rememberLogin.status,200);
  assert.ok(remembered.cookie);
  assert.equal((await request('/api/me','GET',null,remembered)).data.user.id,buyer.id);
  const sessionLogin=await fetch(base+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'buyer@gmail.com',password:'strong-password-123'})});
  assert.equal(sessionLogin.status,200);
  assert.ok(!sessionLogin.headers.get('set-cookie').includes('Max-Age'));
  await request('/api/logout','POST',null,remembered);
  assert.equal((await request('/api/me','GET',null,remembered)).data.user,null);
  assert.equal((await request('/api/listings','POST',{},seller)).status,400);
  const image=new Blob([Uint8Array.from([137,80,78,71,13,10,26,10,0])],{type:'image/png'});
  const sale=new FormData(); for(const [k,v] of Object.entries({kind:'sale',title:'Ders kitabı',description:'Temiz kullanılmış ders kitabı',category:'Ders kitapları',condition:'Az kullanılmış',price:'150'})) sale.set(k,v); sale.append('photos',image,'kitap.png'); sale.append('photos',image,'kitap-arka.png');
  const created=await request('/api/listings','POST',sale,seller); assert.equal(created.status,201);
  const tooManyPhotos=new FormData();for(const [k,v] of Object.entries({kind:'sale',title:'Fazla fotoğraf',description:'Sınır kontrolü',category:'Diğer',condition:'Yeni',price:'10'}))tooManyPhotos.set(k,v);for(let i=0;i<7;i++)tooManyPhotos.append('photos',image,`foto-${i}.png`);
  assert.equal((await request('/api/listings','POST',tooManyPhotos,seller)).status,400);
  const id=created.data.id;
  assert.equal((await request(`/api/listings/${id}`,'PATCH',{title:'Yetkisiz değişiklik'},regular)).status,404);
  assert.deepEqual((await request(`/api/admin/accounts/${seller.id}/listings`,'GET',null,admin)).data.listings.map(l=>l.id),[id]);
  assert.equal((await request(`/api/listings/${id}`,'PATCH',{title:'Yönetici düzenledi'},admin)).status,200);
  assert.equal((await request(`/api/listings/${id}`)).data.listing.title,'Yönetici düzenledi');
  assert.equal((await request(`/api/listings/${id}`,'PATCH',{title:'Ders kitabı'},admin)).status,200);
  assert.equal((await request('/api/mine')).status,401);
  assert.deepEqual((await request('/api/mine','GET',null,buyer)).data.listings,[]);
  assert.deepEqual((await request('/api/mine','GET',null,seller)).data.listings.map(item=>item.id),[id]);
  const detail=(await request(`/api/listings/${id}`)).data.listing;
  assert.equal(detail.title,'Ders kitabı');
  assert.equal(detail.price,15000);
  assert.equal(detail.university,'İstanbul Teknik Üniversitesi');
  assert.equal(detail.images.length,2);
  assert.equal((await fetch(base+'/uploads/'+detail.images[0].filename)).status,200);
  const edit=new FormData();edit.set('title','Ders kitabı');edit.set('category','Giyim');edit.set('condition','Kullanılmış');edit.set('description','Temiz kullanılmış ders kitabı');edit.set('price','150');edit.set('keepPhotos',JSON.stringify([detail.images[1].filename]));edit.append('photos',image,'yeni-kapak.png');
  assert.equal((await request(`/api/listings/${id}`,'PATCH',edit,buyer)).status,404);
  assert.equal((await request(`/api/listings/${id}`,'PATCH',edit,seller)).status,200);
  const edited=(await request(`/api/listings/${id}`)).data.listing;
  assert.equal(edited.images.length,2);
  assert.equal(edited.category,'Giyim');
  assert.equal(edited.condition,'Kullanılmış');
  assert.equal(edited.images[0].filename,detail.images[1].filename);
  assert.notEqual(edited.images[1].filename,detail.images[0].filename);
  assert.equal((await fetch(base+'/uploads/'+detail.images[0].filename)).status,404);
  const emptyEdit=new FormData();emptyEdit.set('keepPhotos','[]');
  assert.equal((await request(`/api/listings/${id}`,'PATCH',emptyEdit,seller)).status,400);
  assert.deepEqual((await request('/api/listings?q=KİTABI')).data.listings.map(l=>l.id),[id]);
  assert.deepEqual((await request('/api/listings?q=kitab%C4%B1')).data.listings.map(l=>l.id),[id]);
  assert.deepEqual((await request('/api/listings?q=dres%20kitab%C4%B1')).data.listings.map(l=>l.id),[id]);
  assert.equal((await request('/api/listings?q=kit')).data.listings.length,1);
  assert.deepEqual((await request('/api/listings?q=temiz')).data.listings.map(l=>l.id),[id]);
  assert.equal((await request('/api/listings?q=bisiklet')).data.listings.length,0);
  assert.equal((await request('/api/listings?category=Elektronik')).data.listings.length,0);
  assert.equal((await request('/api/listings?university=Boğaziçi%20Üniversitesi')).data.listings.length,0);
  assert.deepEqual((await request('/api/listings?university=%C4%B0stanbul%20Teknik%20%C3%9Cniversitesi','GET',null,outsider)).data.listings.map(l=>l.id),[id]);
  assert.equal((await request(`/api/listings/${id}`,'GET',null,outsider)).status,200);
  assert.equal((await request(`/api/listings/${id}/conversation`,'POST',null,seller)).status,400);
  assert.equal((await request(`/api/listings/${id}/conversation`,'POST',null,outsider)).status,200);
  assert.deepEqual((await request(`/api/sellers/${seller.id}/listings`)).data.listings.map(l=>l.id),[id]);
  assert.equal((await request(`/api/listings/${id}/favorite`,'POST',null,buyer)).status,200);
  assert.equal((await request('/api/favorites','GET',null,buyer)).data.listings[0].id,id);
  const conversation=await request(`/api/listings/${id}/conversation`,'POST',null,buyer); assert.equal(conversation.status,200);
  const firstMessage=await request(`/api/conversations/${conversation.data.id}/messages`,'POST',{body:'Merhaba, ürün hâlâ mevcut mu?'},buyer);
  assert.equal(firstMessage.status,201);
  assert.equal((await request('/api/reports','POST',{messageId:firstMessage.data.id,reason:'Uygunsuz mesaj'},outsider)).status,404);
  assert.equal((await request('/api/reports','POST',{messageId:firstMessage.data.id,reason:'Uygunsuz mesaj'},buyer)).status,404);
  assert.equal((await request('/api/reports','POST',{messageId:firstMessage.data.id,reason:'Uygunsuz mesaj'},seller)).status,201);
  assert.ok((await request('/api/admin/queue','GET',null,admin)).data.reports.some(report=>report.message_id===firstMessage.data.id && report.conversation_id===conversation.data.id));
  assert.equal((await request('/api/unread-count','GET',null,seller)).data.count,1);
  assert.equal((await request('/api/unread-count','GET',null,buyer)).data.count,0);
  assert.equal((await request(`/api/conversations/${conversation.data.id}/messages`,'GET',null,seller)).status,200);
  assert.equal((await request('/api/unread-count','GET',null,seller)).data.count,0);
  assert.equal((await request(`/api/conversations/${conversation.data.id}/messages`,'GET',null,admin)).status,404);
  assert.equal((await request(`/api/conversations/${conversation.data.id}/messages`,'GET',null,outsider)).status,404);
  assert.ok(!('messages' in (await request(`/api/listings/${id}`)).data.listing));
  const events=await fetch(base+'/api/message-events',{headers:{cookie:seller.cookie}});
  assert.equal(events.headers.get('content-type').includes('text/event-stream'),true);
  const reader=events.body.getReader(); await reader.read();
  const photoMessage=new FormData(); photoMessage.set('body','Kitabın kapağı'); photoMessage.set('photo',image,'kapak.png');
  const sentPhoto=await request(`/api/conversations/${conversation.data.id}/messages`,'POST',photoMessage,buyer);
  assert.equal(sentPhoto.status,201);
  const liveEvent=await Promise.race([reader.read(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Canlı mesaj gelmedi')),2000))]);
  assert.ok(new TextDecoder().decode(liveEvent.value).includes('conversationId'));
  await reader.cancel();
  assert.equal((await fetch(`${base}/api/messages/${sentPhoto.data.id}/photo`,{headers:{cookie:seller.cookie}})).status,200);
  assert.equal((await fetch(`${base}/api/messages/${sentPhoto.data.id}/photo`,{headers:{cookie:outsider.cookie}})).status,404);
  assert.equal((await fetch(`${base}/api/messages/${sentPhoto.data.id}/photo`)).status,401);
  assert.ok((await request(`/api/conversations/${conversation.data.id}/messages`,'GET',null,seller)).data.messages.some(m=>m.id===sentPhoto.data.id && m.photo_filename));
  const voiceMessage=new FormData();voiceMessage.set('voice',new Blob([Uint8Array.from([0x1a,0x45,0xdf,0xa3,0x42,0x86,0x81,0x01])],{type:'audio/webm'}),'ses.webm');
  const sentVoice=await request(`/api/conversations/${conversation.data.id}/messages`,'POST',voiceMessage,buyer);
  assert.equal(sentVoice.status,201);
  assert.ok((await request(`/api/conversations/${conversation.data.id}/messages`,'GET',null,seller)).data.messages.some(m=>m.id===sentVoice.data.id && m.voice_filename));
  assert.ok((await request('/api/conversations','GET',null,seller)).data.conversations.some(c=>c.id===conversation.data.id && c.last_message.includes('Sesli mesaj')));
  assert.equal((await fetch(`${base}/api/messages/${sentVoice.data.id}/voice`,{headers:{cookie:seller.cookie}})).status,200);
  assert.equal((await fetch(`${base}/api/messages/${sentVoice.data.id}/voice`,{headers:{cookie:outsider.cookie}})).status,404);
  assert.equal((await fetch(`${base}/api/messages/${sentVoice.data.id}/voice`)).status,401);
  assert.equal((await request(`/api/admin/accounts/${buyer.id}/conversations`,'GET',null,buyer)).status,403);
  const reviewList=await request(`/api/admin/accounts/${buyer.id}/conversations`,'GET',null,admin);
  assert.equal(reviewList.status,200);
  assert.ok(reviewList.data.conversations.some(c=>c.id===conversation.data.id));
  assert.equal((await request(`/api/admin/conversations/${conversation.data.id}/review`,'POST',{reason:'short'},admin)).status,400);
  assert.equal((await request(`/api/admin/conversations/${conversation.data.id}/review`,'POST',{reason:'Complaint review'},buyer)).status,403);
  assert.equal((await fetch(`${base}/api/admin/messages/${sentPhoto.data.id}/photo`,{headers:{cookie:admin.cookie}})).status,404);
  const review=await request(`/api/admin/conversations/${conversation.data.id}/review`,'POST',{reason:'Complaint review'},admin);
  assert.equal(review.status,200);
  assert.ok(review.data.messages.some(m=>m.id===sentVoice.data.id));
  assert.equal((await fetch(`${base}/api/admin/messages/${sentPhoto.data.id}/photo`,{headers:{cookie:admin.cookie}})).status,200);
  assert.equal((await fetch(`${base}/api/admin/messages/${sentVoice.data.id}/voice`,{headers:{cookie:admin.cookie}})).status,200);
  assert.equal((await fetch(`${base}/api/admin/messages/${sentPhoto.data.id}/photo`,{headers:{cookie:outsider.cookie}})).status,403);
  const auditDb=new DatabaseSync(path.join(temp,'data','unipazar.sqlite'));
  assert.equal(auditDb.prepare('SELECT COUNT(*) AS count FROM admin_message_reviews WHERE admin_id=? AND conversation_id=?').get(admin.id,conversation.data.id).count,1);
  auditDb.close();

  const meetingAt=new Date(Date.now()+86400000).toISOString().slice(0,16);
  assert.equal((await request(`/api/conversations/${conversation.data.id}/handoff`,'POST',{place:'Kütüphane girişi',meetingAt},buyer)).status,200);
  assert.equal((await request(`/api/conversations/${conversation.data.id}/handoff`,'PATCH',{status:'confirmed'},seller)).status,200);
  const offer=await request(`/api/listings/${id}/offers`,'POST',{amount:100},buyer); assert.equal(offer.status,201);
  assert.equal(offer.data.conversationId,conversation.data.id);
  assert.equal((await request('/api/unread-count','GET',null,seller)).data.count,1);
  assert.ok((await request('/api/conversations','GET',null,seller)).data.conversations.some(c=>c.id===conversation.data.id && c.last_message.includes('fiyat teklifi')));
  assert.equal((await request(`/api/conversations/${conversation.data.id}/messages`,'GET',null,outsider)).status,404);
  const offers=(await request('/api/offers','GET',null,seller)).data.offers;
  assert.equal((await request(`/api/offers/${offers[0].id}`,'PATCH',{status:'accepted'},seller)).status,200);
  assert.equal((await request(`/api/listings/${id}`)).data.listing.status,'reserved');
  const donation=new FormData(); for(const [k,v] of Object.entries({kind:'donation',title:'Ücretsiz raf',description:'Yurt odasına uygun küçük raf',category:'Ev & yurt',condition:'Kullanılmış',price:'0'})) donation.set(k,v); donation.append('photos',image,'raf.png');
  const donated=await request('/api/listings','POST',donation,seller); assert.equal(donated.status,201);
  assert.equal((await request('/api/listings?kind=donation&q=RAF')).data.listings.length,0);
  assert.equal((await request('/api/listings?kind=donation&q=RAF','GET',null,regular)).data.listings.length,0);
  assert.equal((await request(`/api/listings/${donated.data.id}`,'GET',null,regular)).status,404);
  assert.equal((await request(`/api/listings/${donated.data.id}`,'GET',null,seller)).status,200);
  const donationImage=(await request(`/api/listings/${donated.data.id}`,'GET',null,seller)).data.listing.images[0].filename;
  assert.equal((await fetch(base+'/uploads/'+donationImage)).status,404);
  assert.equal((await fetch(base+'/uploads/'+donationImage,{headers:{cookie:seller.cookie}})).status,200);
  assert.ok((await request('/api/mine','GET',null,seller)).data.listings.some(item=>item.id===donated.data.id));
  assert.equal((await request('/api/listings?kind=donation&q=kitap')).data.listings.length,0);
  assert.equal((await request(`/api/listings/${donated.data.id}/requests`,'POST',{note:'İhtiyacım var'},regular)).status,403);
  assert.equal((await request('/api/me','GET',null,buyer)).data.user.needsSupport,false);
  assert.equal((await request('/api/support-application','POST',{reason:'Yurt masraflarını karşılamakta çok zorlanıyorum.',familyIncome:12000,identityLast4:'1234'},buyer)).status,201);
  const supportQueue=(await request('/api/admin/queue','GET',null,admin)).data.support;
  assert.equal(supportQueue.length,1);
  assert.equal(supportQueue[0].email,'buyer@gmail.com');
  assert.equal(supportQueue[0].identity_last4,'1234');
  assert.equal((await request('/api/me','GET',null,buyer)).data.user.needsSupport,false);
  assert.equal((await request('/api/listings?kind=donation','GET',null,buyer)).data.listings.length,0);
  assert.equal((await request('/api/admin/support/'+buyer.id,'PATCH',{status:'approved'},regular)).status,403);
  assert.equal((await request('/api/admin/support/'+buyer.id,'PATCH',{status:'approved'},admin)).status,200);
  assert.deepEqual((await request('/api/listings?kind=donation&q=RAF','GET',null,buyer)).data.listings.map(l=>l.id),[donated.data.id]);
  assert.equal((await request(`/api/listings/${donated.data.id}`,'GET',null,buyer)).status,200);
  assert.equal((await fetch(base+'/uploads/'+donationImage,{headers:{cookie:buyer.cookie}})).status,200);
  assert.equal((await request(`/api/listings/${donated.data.id}`,'GET',null,outsider)).status,404);
  assert.equal((await request('/api/listings?kind=donation','GET',null,outsider)).data.listings.length,0);
  assert.equal((await fetch(base+'/uploads/'+donationImage,{headers:{cookie:outsider.cookie}})).status,404);
  assert.equal((await request('/api/me/support-mode','PATCH',{needsSupport:true},regular)).status,404);
  assert.equal((await request(`/api/listings/${donated.data.id}/requests`,'POST',{note:'Yurt odamda kullanacağım.'},buyer)).status,201);
  const requests=(await request('/api/donation-requests','GET',null,seller)).data.requests;
  assert.equal((await request(`/api/donation-requests/${requests[0].id}`,'PATCH',{status:'accepted'},seller)).status,200);
  assert.equal((await request(`/api/donation-requests/${requests[0].id}`,'PATCH',{status:'completed'},seller)).status,200);
  assert.equal((await request(`/api/listings/${donated.data.id}`,'GET',null,seller)).data.listing.status,'sold');
  const invalidPrice=new FormData(); for(const [k,v] of Object.entries({kind:'sale',title:'Fiyat kontrolü',description:'Fiyat alanı sunucuda denetlenir',category:'Diğer',condition:'Yeni',price:'-1'})) invalidPrice.set(k,v); invalidPrice.append('photos',image,'fiyat.png');
  assert.equal((await request('/api/listings','POST',invalidPrice,seller)).status,400);
  invalidPrice.set('price','1e3');
  assert.equal((await request('/api/listings','POST',invalidPrice,seller)).status,400);
  invalidPrice.set('price','0');
  const freeSale=await request('/api/listings','POST',invalidPrice,seller);
  assert.equal(freeSale.status,201);
  assert.equal((await request(`/api/listings/${freeSale.data.id}`,'GET',null,seller)).data.listing.price,0);
  assert.deepEqual((await request(`/api/sellers/${seller.id}/listings`)).data.listings.map(l=>l.id),[freeSale.data.id]);
  const profileBody={name:'Satıcı Öğrenci',university:'Munzur Üniversitesi'};
  assert.equal((await request('/api/me/profile','PATCH',{...profileBody,university:'Olmayan Üniversite'},seller)).status,400);
  const updated=await request('/api/me/profile','PATCH',profileBody,seller);
  assert.equal(updated.status,200);
  assert.equal(updated.data.user.name,profileBody.name);
  assert.equal(updated.data.user.university,profileBody.university);
  assert.equal((await request('/api/me/phone','PATCH',{phone:'05551234567',password:'wrong'},seller)).status,403);
  assert.equal((await request('/api/me/phone','PATCH',{phone:'05551234567',password:'strong-password-123'},seller)).data.user.phone,'05551234567');
  assert.equal((await request('/api/me/email','PATCH',{email:'new-seller@example.com',password:'wrong'},seller)).status,403);
  const emailChanged=await request('/api/me/email','PATCH',{email:'new-seller@example.com',password:'strong-password-123'},seller);
  assert.equal(emailChanged.status,200);
  assert.equal(emailChanged.data.user.emailVerified,false);
  assert.equal((await request('/api/me/verify-email','POST',{code:'000000'},seller)).status,400);
  assert.equal((await request('/api/me/verify-email','POST',{code:emailChanged.data.devCode},seller)).data.user.emailVerified,true);
  assert.equal((await request('/api/login','POST',{email:'seller@example.com',password:'strong-password-123'})).status,401);
  assert.equal((await request('/api/login','POST',{email:'new-seller@example.com',password:'strong-password-123'})).status,200);
  const expiredCover=(await request(`/api/listings/${freeSale.data.id}`,'GET',null,seller)).data.listing.images[0].filename;
  const testDb=new DatabaseSync(path.join(temp,'data','unipazar.sqlite'));
  testDb.prepare("UPDATE listings SET created_at=datetime('now','-181 days') WHERE id=?").run(freeSale.data.id);
  testDb.prepare("UPDATE listings SET created_at=datetime('now','-181 days') WHERE id=?").run(donated.data.id);
  testDb.close();
  assert.equal((await request(`/api/listings/${freeSale.data.id}`,'GET',null,buyer)).status,404);
  assert.equal((await request(`/api/listings/${freeSale.data.id}`,'GET',null,seller)).data.listing.status,'expired');
  assert.equal((await request(`/api/listings/${donated.data.id}`,'GET',null,seller)).data.listing.status,'sold');
  assert.ok(!(await request('/api/listings','GET',null,buyer)).data.listings.some(item=>item.id===freeSale.data.id));
  assert.ok((await request('/api/mine','GET',null,seller)).data.listings.some(item=>item.id===freeSale.data.id && item.status==='expired'));
  assert.equal((await request(`/api/listings/${freeSale.data.id}`,'PATCH',{status:'active'},seller)).status,409);
  assert.equal((await fetch(`${base}/uploads/${expiredCover}`)).status,404);
  const typoSale=new FormData();for(const [k,v] of Object.entries({kind:'sale',title:'Kiralık örgü çanta',description:'El işi ürün',category:'Diğer',condition:'Yeni',price:'50'}))typoSale.set(k,v);typoSale.append('photos',image,'canta.png');
  const typoCreated=await request('/api/listings','POST',typoSale,seller);assert.equal(typoCreated.status,201);
  assert.deepEqual((await request('/api/listings?q=k%C4%B1ral%C4%B1k')).data.listings.map(l=>l.id),[typoCreated.data.id]);
  assert.deepEqual((await request('/api/listings?q=orgu%20canta')).data.listings.map(l=>l.id),[typoCreated.data.id]);
  assert.deepEqual((await request('/api/listings?q=kiral%C4%B1k%20orgu%20cnta')).data.listings.map(l=>l.id),[typoCreated.data.id]);
  assert.equal((await request('/api/listings?q=bilgisayar')).data.listings.length,0);
  assert.equal((await request('/api/admin/accounts','GET',null,regular)).status,403);
  const accounts=(await request('/api/admin/accounts','GET',null,admin)).data;
  assert.equal(accounts.total,6);
  assert.ok(accounts.accounts.some(account=>account.id===seller.id && account.email==='new-seller@example.com'));
  assert.equal((await request(`/api/admin/accounts/${admin.id}`,'PATCH',{closed:true},admin)).status,403);
  assert.equal((await request(`/api/admin/accounts/${seller.id}`,'PATCH',{closed:true},regular)).status,403);
  assert.equal((await request(`/api/admin/accounts/${seller.id}`,'PATCH',{closed:true},admin)).status,200);
  assert.equal((await request('/api/me','GET',null,seller)).data.user,null);
  assert.equal((await request('/api/login','POST',{email:'new-seller@example.com',password:'strong-password-123'})).status,403);
  assert.equal((await request(`/api/listings/${typoCreated.data.id}`)).status,404);
  assert.equal((await request(`/api/conversations/${conversation.data.id}/messages`,'POST',{body:'Merhaba'},buyer)).status,409);
  assert.equal((await request(`/api/admin/accounts/${seller.id}`,'PATCH',{closed:false},admin)).status,200);
  assert.equal((await request('/api/login','POST',{email:'new-seller@example.com',password:'strong-password-123'})).status,200);
  const secondAdmin=spawnSync(process.execPath,['scripts/grant-admin.js','buyer@gmail.com'],{cwd:process.cwd(),env:{...process.env,DATA_DIR:path.join(temp,'data')},encoding:'utf8'});
  assert.notEqual(secondAdmin.status,0);
});

test('yerel kayıt tüm alanları ister, hesabı açar ve girişe izin verir', async t => {
  const temp=mkdtempSync(path.join(os.tmpdir(),'unipazar-local-'));
  const port=32000+Math.floor(Math.random()*1000);
  const base=`http://127.0.0.1:${port}`;
  const server=spawn(process.execPath,['server.js','--local'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),DATA_DIR:path.join(temp,'data'),UPLOAD_DIR:path.join(temp,'uploads'),ADMIN_EMAIL:'admin@unipazar.local',NODE_ENV:'production',TEST_EMAIL_CODES:'',SMTP_HOST:'',SMTP_FROM:'',LEGAL_ENABLED:'1',LEGAL_CONTROLLER_NAME:'Test İşletmecisi',LEGAL_CONTACT_EMAIL:'privacy@example.com'},stdio:'ignore'});
  t.after(async()=>{await new Promise(resolve=>{server.once('exit',resolve);server.kill();setTimeout(resolve,1500);});rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100});});
  for(let i=0;i<50;i++){try{if((await fetch(base+'/api/me')).ok)break;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}
  const post=async(path,body,cookie)=>{const res=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json',...(cookie?{cookie}:{})},body:JSON.stringify(body)});return {status:res.status,data:await res.json(),setCookie:res.headers.get('set-cookie'),cookie:res.headers.get('set-cookie')?.split(';')[0]};};
  const legalVersion=(await (await fetch(base+'/api/me')).json()).legalVersion;
  const details={name:'Deniz',email:'deniz@gmail.com',university:'Munzur Üniversitesi',password:'strong-password-123',phone:'05551234567',rememberMe:true,termsAccepted:true,privacyRead:true,legalVersion};
  assert.equal((await post('/api/register',{...details,termsAccepted:false})).status,400);
  assert.equal((await post('/api/register',{...details,privacyRead:false})).status,400);
  assert.equal((await post('/api/register',{...details,legalVersion:'old-version'})).status,400);
  assert.equal((await post('/api/register',{...details,google:true})).status,400);
  const privacy=await fetch(base+'/legal/privacy');assert.equal(privacy.status,200);assert.ok((await privacy.text()).includes('privacy@example.com'));
  assert.equal((await post('/api/register',{...details,name:''})).status,400);
  assert.equal((await post('/api/register',{...details,university:''})).status,400);
  assert.equal((await post('/api/register',{...details,email:''})).status,400);
  assert.equal((await post('/api/register',{...details,password:''})).status,400);
  assert.equal((await post('/api/register',{...details,phone:''})).status,400);
  assert.equal((await post('/api/register',{...details,phone:'123'})).status,400);
  const invalid=await post('/api/register',{...details,name:'',email:'hatalı',university:'Olmayan üniversite',phone:'123',password:'kısa'});
  assert.equal(invalid.status,400);
  assert.deepEqual(Object.keys(invalid.data.fields).sort(),['email','name','password','phone','university']);
  const registered=await post('/api/register',details);
  assert.equal(registered.status,201);
  assert.equal(registered.data.user.name,'Deniz');
  assert.equal(registered.data.user.phone,details.phone);
  assert.equal(registered.data.user.emailVerified,false);
  assert.ok(registered.cookie);
  assert.ok(!registered.setCookie.includes('Max-Age'));
  const auditDb=new DatabaseSync(path.join(temp,'data','unipazar.sqlite'));
  const acceptance=auditDb.prepare('SELECT * FROM registration_acceptances WHERE user_id=?').get(registered.data.user.id);
  assert.equal(acceptance.version,legalVersion);assert.ok(acceptance.accepted_at);assert.equal(JSON.parse(acceptance.documents).privacy.title,'KVKK Aydınlatma Metni');auditDb.close();
  assert.equal((await (await fetch(base+'/api/me',{headers:{cookie:registered.cookie}})).json()).user.email,details.email);
  const duplicate=await post('/api/register',details);
  assert.equal(duplicate.status,409);
  assert.ok(duplicate.data.fields.email);
  assert.equal((await post('/api/login',{email:details.email,password:'wrong'})).status,401);
  assert.equal((await post('/api/login',{email:details.email,password:details.password})).status,200);
  const admin=await post('/api/register',{...details,name:'Yönetici',email:'admin@unipazar.local'});
  assert.equal(admin.status,201);
  assert.equal(admin.data.user.role,'student');
  grantAdmin('admin@unipazar.local',path.join(temp,'data'));
  const accountList=await fetch(base+'/api/admin/accounts',{headers:{cookie:admin.cookie}});
  assert.equal(accountList.status,200);
  assert.equal((await accountList.json()).total,2);
});
