import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {DatabaseSync} from 'node:sqlite';import {scryptSync,createHash} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
test('login survives browser restarts, renews live sessions and cannot revive revoked or expired sessions',async t=>{
 const temp=mkdtempSync(path.join(os.tmpdir(),'unisatis-session-')),port=41000+Math.floor(Math.random()*500),base=`http://127.0.0.1:${port}`;
 const server=spawn(process.execPath,['server.js','--local'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),NODE_ENV:'test',DATA_DIR:path.join(temp,'data'),UPLOAD_DIR:path.join(temp,'uploads'),BACKUP_ENABLED:'0'},stdio:'ignore'});let db;
 t.after(async()=>{db?.close();server.kill();await new Promise(resolve=>{server.once('exit',resolve);setTimeout(resolve,1500);});rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100});});
 let ready=false;for(let i=0;i<150;i++){try{if((await fetch(base+'/api/me')).ok){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}assert.ok(ready);
 db=new DatabaseSync(path.join(temp,'data','unipazar.sqlite'));const password='test:'+scryptSync('TestPassword1!','test',64).toString('hex');db.prepare('INSERT INTO users(name,email,password_hash,university,campus,email_verified) VALUES(?,?,?,?,?,1)').run('Tester','session@example.invalid',password,'Munzur Üniversitesi','');
 const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'session@example.invalid',password:'TestPassword1!',rememberMe:false})});assert.equal(login.status,200);const setCookie=login.headers.get('set-cookie');assert.match(setCookie,/Max-Age=15552000/);assert.match(setCookie,/HttpOnly/);const cookie=setCookie.split(';')[0],token=cookie.slice('up_session='.length),hash=createHash('sha256').update(token).digest('hex');
 db.prepare('UPDATE sessions SET expires_at=? WHERE token_hash=?').run(Date.now()+60000,hash);const restored=await fetch(base+'/api/me',{headers:{cookie}});assert.ok((await restored.json()).user);assert.match(restored.headers.get('set-cookie'),/Max-Age=15552000/);assert.ok(db.prepare('SELECT expires_at FROM sessions WHERE token_hash=?').get(hash).expires_at>Date.now()+179*86400000);
 await fetch(base+'/api/logout',{method:'POST',headers:{cookie}});assert.equal((await (await fetch(base+'/api/me',{headers:{cookie}})).json()).user,null);
 db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash,1,Date.now()-1);const expired=await fetch(base+'/api/me',{headers:{cookie}});assert.equal((await expired.json()).user,null);assert.equal(expired.headers.get('set-cookie'),null);
});
