import webpush from 'web-push';
import {ECDH} from 'node:crypto';
export function validSubscription(value){
 try{const url=new URL(value?.endpoint);const host=url.hostname; if(url.protocol!=='https:'||url.username||url.password||url.port||!['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].includes(host)&&!host.endsWith('.notify.windows.com'))return false;if(value.endpoint.length>2048)return false;const key=Buffer.from(value.keys?.p256dh||'','base64url'),auth=Buffer.from(value.keys?.auth||'','base64url');if(key.length!==65||auth.length!==16)return false;ECDH.convertKey(key,'prime256v1');return true;}catch{return false;}
}
export function registerNotifications({app,db,requireUser,fail,hash,sendPush=webpush.sendNotification.bind(webpush)}){
 db.exec(`CREATE TABLE IF NOT EXISTS notification_keys(name TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS push_subscriptions(endpoint TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,session_hash TEXT NOT NULL REFERENCES sessions(token_hash) ON DELETE CASCADE,subscription TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS push_queue(message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,endpoint TEXT NOT NULL REFERENCES push_subscriptions(endpoint) ON DELETE CASCADE,recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,payload TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL DEFAULT 0,expires_at INTEGER NOT NULL,PRIMARY KEY(message_id,endpoint));`);
 let keys=db.prepare("SELECT value FROM notification_keys WHERE name='vapid'").get();if(!keys){const generated=webpush.generateVAPIDKeys();db.prepare("INSERT INTO notification_keys VALUES('vapid',?)").run(JSON.stringify(generated));keys={value:JSON.stringify(generated)};}keys=JSON.parse(keys.value);webpush.setVapidDetails('mailto:unisatis06@gmail.com',keys.publicKey,keys.privateKey);
 const latest=user=>db.prepare(`SELECT m.id,m.conversation_id,m.sender_id FROM messages m JOIN conversations c ON c.id=m.conversation_id WHERE (c.buyer_id=? OR c.seller_id=?) AND m.sender_id<>? ORDER BY m.id DESC LIMIT 1`).get(user.id,user.id,user.id)||null;
 app.get('/api/notifications/status',(req,res)=>{const user=requireUser(req,res);if(!user)return;res.json({publicKey:keys.publicKey,latest:latest(user)});});
 app.post('/api/notifications/subscribe',(req,res)=>{const user=requireUser(req,res);if(!user)return;if(req.headers.origin&&req.headers.origin!==`${req.protocol}://${req.get('host')}`)return fail(res,403,'Bildirim isteği aynı uygulamadan gelmeli.');if(!validSubscription(req.body))return fail(res,400,'Geçersiz bildirim aboneliği.');const token=/(?:^|; )up_session=([^;]+)/.exec(req.headers.cookie||'')?.[1];if(!token)return fail(res,401,'Önce giriş yap.');if(db.prepare('SELECT count(*) AS n FROM push_subscriptions WHERE user_id=?').get(user.id).n>=10&&!db.prepare('SELECT 1 FROM push_subscriptions WHERE endpoint=?').get(req.body.endpoint))return fail(res,400,'En fazla 10 cihaz için bildirim açılabilir.');db.prepare(`INSERT INTO push_subscriptions(endpoint,user_id,session_hash,subscription) VALUES(?,?,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,session_hash=excluded.session_hash,subscription=excluded.subscription`).run(req.body.endpoint,user.id,hash(token),JSON.stringify({endpoint:req.body.endpoint,keys:req.body.keys}));res.json({ok:true});});
 app.delete('/api/notifications/subscribe',(req,res)=>{const user=requireUser(req,res);if(!user)return;db.prepare('DELETE FROM push_subscriptions WHERE endpoint=? AND user_id=?').run(String(req.body.endpoint||''),user.id);res.json({ok:true});});
 const startupMax=db.prepare('SELECT COALESCE(max(id),0) AS n FROM messages').get().n,delivered=new Map();
 async function notify(conversation,senderId){const message=db.prepare('SELECT id,sender_id FROM messages WHERE conversation_id=? ORDER BY id DESC LIMIT 1').get(conversation.id);if(!message||message.id<=startupMax||message.id<=(delivered.get(conversation.id)||0)||message.sender_id!==senderId)return;delivered.set(conversation.id,message.id);if(delivered.size>10000)delivered.delete(delivered.keys().next().value);const recipient=conversation.buyer_id===senderId?conversation.seller_id:conversation.buyer_id;if(!recipient)return;const subscriptions=db.prepare('SELECT p.* FROM push_subscriptions p JOIN sessions s ON s.token_hash=p.session_hash JOIN users u ON u.id=p.user_id WHERE p.user_id=? AND s.expires_at>? AND u.closed_at IS NULL').all(recipient,Date.now());const payload=JSON.stringify({title:'Üni Satış · Yeni mesaj',body:'Üni Satış’ta yeni bir mesajın var.',conversationId:conversation.id,messageId:message.id,userId:recipient,url:`/?conversation=${conversation.id}#/messages`});for(const row of subscriptions)db.prepare('INSERT OR IGNORE INTO push_queue(message_id,endpoint,recipient_id,payload,expires_at) VALUES(?,?,?,?,?)').run(message.id,row.endpoint,recipient,payload,Date.now()+3600000);await flush();}
 let sending=false;
 async function flush(){if(sending)return;sending=true;try{db.prepare('DELETE FROM push_queue WHERE expires_at<? OR attempts>=3').run(Date.now());const rows=db.prepare('SELECT q.*,p.subscription FROM push_queue q JOIN push_subscriptions p ON p.endpoint=q.endpoint AND p.user_id=q.recipient_id JOIN sessions s ON s.token_hash=p.session_hash JOIN users u ON u.id=p.user_id WHERE s.expires_at>? AND u.closed_at IS NULL AND q.next_attempt<=? LIMIT 20').all(Date.now(),Date.now());await Promise.allSettled(rows.map(async row=>{try{await sendPush(JSON.parse(row.subscription),row.payload,{TTL:3600,urgency:'high',timeout:10000});db.prepare('DELETE FROM push_queue WHERE message_id=? AND endpoint=?').run(row.message_id,row.endpoint);}catch(error){if([404,410].includes(error.statusCode))db.prepare('DELETE FROM push_subscriptions WHERE endpoint=?').run(row.endpoint);else db.prepare('UPDATE push_queue SET attempts=attempts+1,next_attempt=? WHERE message_id=? AND endpoint=?').run(Date.now()+60000,row.message_id,row.endpoint);}}));}finally{sending=false;}}
 setInterval(()=>flush().catch(()=>{}),30000).unref();return {notify,flush};
}
